name: "Create .app files out of binaries macOS"
description: "Create .app files out of binaries macOS"
inputs:
  APPNAME:
    description: "APPNAME"
    required: true
  ICONNAME:
    description: "ICONNAME"
    required: true
  BUNDLEID:
    description: "BUNDLEID"
    required: true
  VERSIONNO:
    description: "VERSIONNO"
    required: true
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo "Hello. Starting Action now."
      shell: bash
    - name: "Create the app file"
      id: generate-app
      run: |
        ls -al
        cp ${{ github.action_path }}/setup.sh setup.sh
        chmod +x setup.sh
        ls -al
        ./setup.sh "${{ inputs.APPNAME }}" ${{ inputs.ICONNAME }} ${{ inputs.BUNDLEID }} ${{ inputs.VERSIONNO }}
      shell: bash
    - run: cp ${{ inputs.APPNAME }} ${{ inputs.APPNAME }}.app/Contents/MacOS/MyNewApp
      shell: bash
